image: Visual Studio 2019

install:
  - gitversion /l console /output buildserver
  - dotnet tool install -g codecov.tool

configuration:
  - Release

dotnet_csproj:
  patch: true
  version: '$(GitVersion_SemVer)'

build_script:
  - cmd: dotnet pack

after_build:
  - appveyor PushArtifact src\ReportPortal.Shared\bin\%configuration%\ReportPortal.Shared.%GitVersion_SemVer%.nupkg

test_script:
  - cmd: dotnet test --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=OpenCover /p:CoverletOutput=./Coverage.xml

after_test:
  - codecov -f test/ReportPortal.Shared.Tests/Coverage.*.xml
  - dotnet run -c Release --project test/ReportPortal.Shared.Benchmark

artifacts:
  - path: '**\*.html'