image: Visual Studio 2017

install:
  - ps: gitversion /l console /output buildserver

configuration:
  - Release

dotnet_csproj:
  patch: true
  version: '$(GitVersion_NuGetVersion)'

build_script:
  - cmd: dotnet build

test_script:
  - cmd: dotnet test --no-build

after_test:
  - cmd: dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg

artifacts:
  - path: '**\*.nupkg'
  - path: '**\*.snupkg'